### ISSUE TITLE
Libraries aren't loaded in the script

### ISSUE THREAD

**Issue by RobLytle** [pos5737/hw01-taylor-chewning#2]
SHA: `bc7f5fbd3aca15ef1d59a69c0b58647e1ef0f0c1`

The [script for your interesting example project](
https://github.com/pos5737/hw01-taylor-chewning/blob/master/interesting%20example%20project%20bar%20chart.R) does not run by default, remember that packages must be loaded every time R starts! This is an easy mistake to make (and fix), you likely loaded them earlier in your session and thus didn't realize the commands weren't included in the script.

**Comment by carlislerainey** [comment]
@RobLytle This is an excellent, excellent catch, but you should give a few more details, especially since we haven’t talked about R code at all yet. 

- Why does she need to load a package at all?
- What packages does @taylorkchewning need to load? 
- How does one load packages in R? 
- Where do you recommend she put the line of code (all at top or distributes throughout)? 
- Perhaps point her to an example script that loads packages. 

We haven’t talked at all about R so far, so I don’t expect anyone to know what a “package” is, for example.

**Comment by RobLytle** [comment]
Good point, I put a few more details in the review but suppose I should have put them here instead!

A package is a set of functions that can be added to R that allows the coder to do things that the basic R cannot do. For example, the `ggplot()` function that you use in your "something interesting" requires a new package (`ggplot2`) to be loaded, as the code that allows R to make a `ggplot` is part of the package, not of basic R. Notice in Carlisle's example script (create-plot.R) he uses `qplot`, not `ggplot` --- `qplot` is a function of the `tidyverse` package which is loaded at the top of that script.

#### There are two steps to setting up packages in your R script, **installing** and **loading**

- To **install** a script you can use the code snippet `install.package("package_name")` in the RStudio console or you can just navigate to the package under the "packages" tab on the right hand side of the Graphical User Interface (GUI). Technically, you could include `install.package("package_name")` in your script but it is considered rude to install a package on somebody else's computer. You only have to install a script once per computer.

- The second step to using a package is to **load** it. This is necessary to do each time you start a new session of RStudio, assuming you want to use functions not found in the basic R distribution (which we likely will for all of our projects). To load a package add the line `library(package_name)` to your script, or type it in the console. If you tell RStudio to load `ggplot2` you are telling it to make use of the functions found in the library called `ggplot2`.

Unlike installing a package it is considered good practice to load all of the packages your script requires at the top of the script using the `library(package_name)` syntax. If the person running your script has the packages installed on their computer this lets RStudio use them seamlessly, and if they are not installed it tells the user which packages they'll have to install to use your script.

**Comment by taylorkchewning** [comment]
Thank you @RobLytle for your insight!  I have made the change to my script to load the package my code used, and did not include the "Install package" command (thanks for letting me know it would be rude to install it on someone else's computer!)

**Comment by carlislerainey** [comment]
*Just FYI, @RobLytle: It's fine to direct when reviewing homework projects. The explanation is also important (and your's is 💯), so I definitely want that in there. But the author might also need the concrete fix to make sense of the abstract/conceptual solution. Feel free to include something like the following in the future:*
 
Add the following code to the top of `interesting example project bar chart.R`:

```
# load packages
library(ggplot2)
```

**Comment by carlislerainey** [comment]
@taylorkchewning, it seems like you fixed the issue with 4818f757418098c38eb89bbc30335c807c7b1256. If that's the case, you can click the *Close* button below.

**Comment by taylorkchewning** [comment]
Yes, I fixed the issue! I'll close this now
